### ISSUE TITLE
minigun should support different environments

### ISSUE THREAD

**Issue by gajjargaurav** [artilleryio/minigun#2]
I want to be able to run the same scenario across multiple environments. I can easily copy the json file per environment or use the json file as template for all scenarios I want to run.
e.g. the target might be 
* **http://localhost:8080** for local 
* **http://developmentdomain** for development environment
* **http://stagingdomain** for staging environment 
* **http:livedomain**  for live/production environment
but the actual URL that follows or data/body/payload could be same.

**Comment by gajjargaurav** [comment]
I am thinking of using [config](https://github.com/lorenwest/node-config) which allows to setup config files per environment and [json-templater](https://github.com/lightsofapollo/json-templater) which will allow us to use the test script as a template such that,
a config file for development environment would look like, 

```json
{
  "minigun": {
    "config": {
      "target": "http://deveopmentdomain"
    }, 
   "scenario": {
       ...
    }
  }
}
```
and config for live environment would look like,
```json
{
  "minigun": {
    "config": {
      "target": "http://livedomain"
    }, 
   "scenario": {
       ...
    }
  }
}
```

Notice that the configuration is set as "minigun" as the client app for testing is going to set the configuration for "minigun" to use

**Comment by gajjargaurav** [comment]
first commit towards that on a fork https://github.com/gajjargaurav/minigun/commit/6c6823c61d6e39cbadf2d5d1d95199e541bfbf2c

**Comment by hassy** [comment]
@gajjargaurav This is a very good suggestion for a common use-case, however I feel that introducing JSON templating into Minigun is an over-complication. There should be another (simpler) way of separating config from scenario definitions, I'll have a think and I'm open to suggestions. :)

**Comment by gajjargaurav** [comment]
@hassy I agree, it isn't something core to minigun and can be abstracted away from it to keep it environment agnostic. A wrapper can be built or leave it to cleint apps to handle the environments. However I think that having it as a feature of minigun isn't too bad either.

**Comment by hassy** [comment]
@gajjargaurav How about being able to set (or override) values in the `config` section of a script? For example, with something like:

```
minigun run -o target=http://staging.app mytest.js
```

(This could be extended to work for any value that can be specified in the `config` section.)

**Comment by gajjargaurav** [comment]
I'd like both  :blush:

**Comment by hassy** [comment]
Another option is to allow environment definitions with something like this:

```javascript
{
  "config": {
    "environments": {
      "local": {
        "target": "http://localhost:8080",
        "defaults": {
          "headers": {
            "x-auth": "abcdef01234567"
          }
        }
      },
      "dev": {},
      "staging": {},
      "production": {}
    }
  },
  "scenarios": [
  ]
}
```

And to run the scenarios in a specific environment:

```shell
minigun run -e local myscript.json
```

So environments are identified by an arbitrary name, and each of them can contain the options currently supported inside the `config` definition.

The `config` section can still be used just like now, and those values will be:
- used if no environment is specified
- over-ridden by values from the environment if specified when running the test

**Comment by gajjargaurav** [comment]
@hassy I like your idea. This should be an easy implementation too :+1:

**Comment by hassy** [comment]
Initial support has been implemented, but the code needs more tests before I merge it.
