### ISSUE TITLE
Generating graphical reports from JSON reports

### ISSUE THREAD

**Issue by hassy** [artilleryio/minigun#4]
Minigun should provide the ability to generate graphical reports from the JSON reports created by `minigun run`.

Requirements:
- The report should show all metrics from the JSON file.
- The report should be a self-contained HTML file that can be copied, emailed, embedded in a Jenkins build report with the [HTML Publisher Plugin](https://wiki.jenkins-ci.org/display/JENKINS/HTML+Publisher+Plugin) etc.

To generate a report:

```
minigun report minigun_report_20150806_115304.json
```

This will create the HTML file in current working directory and open it in the default browser.

**Comment by hassy** [comment]
Initial implementation in https://github.com/artilleryio/minigun/commit/b174ac27b6a9387e417c581aed9a8ad9535fedbf :tophat:  

![https://cldup.com/PYeZJTCe86-1200x1200.png](https://cldup.com/PYeZJTCe86-1200x1200.png)

**Comment by Rahul-012** [comment]
@hassy  as i am new to artillery i found this tool very interesting and want to use this tool for my application  all the set up has been done. Suppose i want to check login application for multiple users so what will be my scenario plz tell me as i am completely new .. any help will be greatly appreciated

**Comment by hassy** [comment]
@Rahul-012 I would suggest reading through the docs first, start here: https://artillery.io/docs/getting-started/ The docs contain everything you'd need to know.

**Comment by Rahul-012** [comment]
@hassy  i already read it i have a performed a simple operation and generate some reports but the problem is Scenario created, Scenario Completed Counter is not incremented  plz take a look at the below Snap-shot  or Correct me If i am wrong 
![screenshot 171](https://cloud.githubusercontent.com/assets/17723293/16906511/b3986034-4cd6-11e6-8c5f-eae7113dedf1.png)
